export const PermissionCodes = {
  UserManage: 'USER_MANAGE',
  RoleManage: 'ROLE_MANAGE',
  AuditLogView: 'AUDIT_LOG_VIEW',
  NotificationView: 'NOTIFICATION_VIEW',
  NotificationManage: 'NOTIFICATION_MANAGE',
  StoreManage: 'STORE_MANAGE',
  StoreView: 'STORE_VIEW',
  PosSaleCreate: 'POS_SALE_CREATE',
  PosSaleView: 'POS_SALE_VIEW',
  PosProductCreate: 'POS_PRODUCT_CREATE',
  PosProductUpdate: 'POS_PRODUCT_UPDATE',
  PosCatalogView: 'POS_CATALOG_VIEW',
  PosCategoryManage: 'POS_CATEGORY_MANAGE',
  PosDiscountManage: 'POS_DISCOUNT_MANAGE',
  PosDiscountApply: 'POS_DISCOUNT_APPLY',
  PosInventoryManage: 'POS_INVENTORY_MANAGE',
  PosStocktakeManage: 'POS_STOCKTAKE_MANAGE',
  PosReturnCreate: 'POS_RETURN_CREATE',
  ReportView: 'REPORT_VIEW',
} as const;
